use_frameworks!

target 'Example' do
   platform :ios, '13'
   pod 'Shift4'
   pod 'SwiftLint', '0.41.0'
end

target 'Example ObjC' do
   platform :ios, '13'
   pod 'Shift4'
   pod 'SwiftLint', '0.41.0'
end
